name: Update LazyVim Plugins

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'scripts/update-plugins.sh'
      - 'scripts/parse-plugins.lua'
      - '.github/workflows/update-plugins.yml'

jobs:
  update-plugins:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v26
        
      - name: Setup Nix cache
        uses: cachix/cachix-action@v12
        with:
          name: nix-community
          
      - name: Check for LazyVim updates
        id: check-updates
        run: |
          # Get current version from plugins.json
          if [ -f plugins.json ]; then
            CURRENT_VERSION=$(jq -r '.version' plugins.json)
            CURRENT_COMMIT=$(jq -r '.commit' plugins.json)
          else
            CURRENT_VERSION="none"
            CURRENT_COMMIT="none"
          fi
          
          # Get latest LazyVim version
          LATEST_VERSION=$(git ls-remote --tags https://github.com/LazyVim/LazyVim.git | grep -v '\^{}' | tail -1 | sed 's/.*\///')
          LATEST_COMMIT=$(git ls-remote https://github.com/LazyVim/LazyVim.git HEAD | cut -f1)
          
          echo "Current version: $CURRENT_VERSION ($CURRENT_COMMIT)"
          echo "Latest version: $LATEST_VERSION ($LATEST_COMMIT)"
          
          if [ "$CURRENT_COMMIT" != "$LATEST_COMMIT" ]; then
            echo "update_needed=true" >> $GITHUB_OUTPUT
            echo "latest_version=$LATEST_VERSION" >> $GITHUB_OUTPUT
          else
            echo "update_needed=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Update plugins
        if: steps.check-updates.outputs.update_needed == 'true'
        run: |
          nix develop --command ./scripts/update-plugins.sh
          
      - name: Create Pull Request
        if: steps.check-updates.outputs.update_needed == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update LazyVim plugins to ${{ steps.check-updates.outputs.latest_version }}"
          title: "Update LazyVim plugins to ${{ steps.check-updates.outputs.latest_version }}"
          body: |
            This PR updates the LazyVim plugin specifications to the latest version.
            
            ## Changes
            - Updated `plugins.json` with latest LazyVim plugin list
            - Version: ${{ steps.check-updates.outputs.latest_version }}
            
            ## Checklist
            - [ ] Review plugin changes
            - [ ] Test with example configuration
            - [ ] Update plugin mappings if needed
            
            ---
            *This pull request was automatically generated by the update workflow.*
          branch: update-lazyvim-plugins
          delete-branch: true
          
  test-flake:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nixpkgs:
          - nixos-unstable
          - nixos-23.11
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v26
        
      - name: Test flake
        run: |
          # Check flake
          nix flake check
          
          # Build the update script
          nix build .#default
          
          # Test the home-manager module evaluation
          nix eval .#homeManagerModules.default --apply 'module: if builtins.isAttrs module then "Module loads successfully" else "Failed to load module"'